org: marty8zhang
app: demo-serverless-express
service: demo-serverless-express

frameworkVersion: '^2'
useDotenv: true

provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: '20201221'
    stage: dev
    region: ap-southeast-2
    profile: serverless-test
    memorySize: 128
    # AWS API Gateway max timeout is 30 secs.
    timeout: 30
    versionFunctions: false
    tags:
        serverless: ''
    environment:
        DB_HOST: ${env:DB_HOST}
        DB_PORT: ${env:DB_PORT}
        DB_USER: ${env:DB_USER}
        DB_PASSWORD: ${env:DB_PASSWORD}
        DB_DATABASE: ${env:DB_DATABASE}

functions:
    testServerlessExpress:
        handler: dist/handler.handler
        events:
            -   http:
                    path: /
                    method: ANY
            -   http:
                    path: /{proxy+}
                    method: ANY
        vpc:
            securityGroupIds:
                - sg-0921d8779a6b3fecf
            subnetIds:
                - subnet-9c4492fb

plugins:
    - serverless-offline
